# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ feature/SetUpEnvironmentVisualCode ]
  pull_request:
    branches: [ feature/SetUpEnvironmentVisualCode ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    
    - name: Create a google-services.json
      uses: jsdaniell/create-json@1.1.2
        with:
          name: "./app/google-services.json"
          json: ${{ secrets.GOOGLE_SERVICES }}
    - uses: actions/upload-artifact@v1
      with:
        name: log
        path: ./app/google-services.json

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew build